<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "article_images".
 *
 * @property integer $id
 * @property integer $parent_id
 * @property string $name
 */
class ArticleImages extends \yii\db\ActiveRecord
{
    public $del = false;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'article_images';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
//            [['article_id', 'name'], 'required'],
            [['parent_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['del'], 'boolean'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => 'Article ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticle()
    {
        return $this->hasOne(Article::className(), ['id' => 'parent_id']);
    }

    public function beforeDelete()
    {
        $path = Yii::getAlias('@upImages') . "/article/{$this->parent_id}/{$this->name}";
        if (file_exists($path)) {
            Yii::$app->mycomponent->myDeleteFile($path);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
