<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "film_images".
 *
 * @property integer $id
 * @property integer $parent_id
 * @property string $name
 */
class FilmImages extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'film_images';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['parent_id', 'name'], 'required'],
            [['parent_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'parent_id' => 'Parent ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArticle()
    {
        return $this->hasOne(Film::className(), ['id' => 'parent_id']);
    }

    public function beforeDelete()
    {
        $path = Yii::getAlias('@upImages') . "/film/{$this->parent_id}/{$this->name}";
        if (file_exists($path)) {
            Yii::$app->mycomponent->myDeleteFile($path);
        }
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
}
